import Header from "@/components/Header";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="mx-auto max-w-3xl px-4 pt-28 pb-20">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        <div className="prose prose-invert max-w-none space-y-6 text-foreground/80">
          <p className="text-sm text-muted">Last updated: February 21, 2026</p>

          <section>
            <h2 className="text-xl font-bold text-white mt-6 mb-3">1. Service Description</h2>
            <p>RoastMyResume is an AI-powered resume review and optimization service. We provide:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Free humorous resume analysis (&ldquo;roast&rdquo;)</li>
              <li>Paid professional resume rewriting and optimization</li>
              <li>ATS (Applicant Tracking System) compatibility scoring</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mt-6 mb-3">2. AI-Generated Content</h2>
            <p>All roasts, rewrites, and suggestions are generated by artificial intelligence (Claude by Anthropic). While we strive for high quality:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>AI output should be reviewed and edited by you before use</li>
              <li>We do not guarantee job placement or interview success</li>
              <li>The roast is entertainment - please do not take it personally</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mt-6 mb-3">3. Payments & Refunds</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>All payments are processed securely through Stripe</li>
              <li>Prices are in USD and include all applicable taxes</li>
              <li>Digital products are delivered instantly after payment</li>
              <li>Refunds are available within 48 hours if you are unsatisfied with the quality</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mt-6 mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Upload content that is illegal, harmful, or violates others&apos; rights</li>
              <li>Attempt to reverse-engineer or abuse the AI system</li>
              <li>Use automated tools to mass-submit resumes</li>
              <li>Resell or redistribute the AI-generated content commercially</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mt-6 mb-3">5. Intellectual Property</h2>
            <p>You retain full ownership of your resume content. The AI-generated rewrite becomes yours to use freely for personal job applications.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mt-6 mb-3">6. Limitation of Liability</h2>
            <p>RoastMyResume is provided &ldquo;as is&rdquo; without warranties. We are not liable for any damages arising from use of the service, including but not limited to lost job opportunities.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mt-6 mb-3">7. Contact</h2>
            <p>Questions about these terms? Email us at: <a href="mailto:punchthewolf@gmail.com" className="text-accent hover:underline">punchthewolf@gmail.com</a></p>
          </section>
        </div>
      </main>
    </div>
  );
}
